"""Provision an isolated, safe trial tenant after Cognito confirmation.

This Lambda is a post-confirmation boundary. Cognito proves the identity; the
trigger creates the server-owned tenant mapping and conservative starter
configuration. No tenant identifier, policy, credential, or privilege is
accepted from signup form data.
"""

import hashlib
import json
import os
import secrets
import time
from typing import Any


def build_trial_records(
    subject: str, email: str, *, now: int | None = None, trial_days: int = 14
) -> list[dict[str, Any]]:
    """Return deterministic-shape, credential-free records for a new trial.

    The tenant ID is generated by the trusted service, not supplied by the
    user. Keeping this builder pure makes the security-critical defaults easy
    to test without AWS credentials.
    """
    if not subject or len(subject) > 128:
        raise ValueError("a valid Cognito subject is required")
    timestamp = int(time.time()) if now is None else int(now)
    expires = timestamp + (trial_days * 86400)
    tenant = f"trial-{secrets.token_hex(16)}"
    safe_policy = {
        "runtime": {"maxActions": 25, "allowedTools": ["read_repository"]},
        "tools": {"allowed": ["read_repository"], "denied": []},
        "policy": {"denyByDefault": True},
        "audit": {"redactSensitiveData": True, "captureToolContent": False},
        "claudeCode": {
            "allowedBuiltInTools": ["Read", "Glob", "Grep"],
            "fileTools": ["Read", "Glob", "Grep"],
            "deniedCommandPatterns": [r"rm\s+-rf"],
            "approvalCommandPatterns": [r"git\s+push"],
            "allowedCommandPatterns": [
                r"^pwd$",
                r"^ls$",
                r"^git[ \t]+status$",
                r"^git[ \t]+status[ \t]+--short$",
                r"^git[ \t]+diff[ \t]+--stat$",
                r"^git[ \t]+log[ \t]+--oneline$",
            ],
        },
    }
    base = {"tenant_id": tenant, "trial": True, "trial_expires_at": expires}
    policy_digest = hashlib.sha256(
        json.dumps(safe_policy, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()
    return [
        {
            "pk": f"USER#{subject}",
            "sk": "TENANT",
            "tenant_id": tenant,
            "email": email,
            "trial": True,
            "created_at": timestamp,
            "expires_at": expires,
        },
        {
            "pk": f"TENANT#{tenant}",
            "sk": "TENANT#root",
            **base,
            "id": tenant,
            "status": "active",
            "created_at": timestamp,
        },
        {
            "pk": f"TENANT#{tenant}",
            "sk": "ORG#org-trial",
            **base,
            "id": "org-trial",
            "name": "Trial workspace",
            "created_at": timestamp,
        },
        {
            "pk": f"TENANT#{tenant}",
            "sk": "POLICY#policy-safe-default",
            **base,
            "id": "policy-safe-default",
            "organization_id": "org-trial",
            "name": "Safe default policy",
            "configuration": safe_policy,
            "version": 1,
            "activeVersion": 1,
            "latestVersion": 1,
            "governanceState": "active",
            "pendingVersion": None,
            "pendingAuthor": None,
            "governance_schema_version": 1,
            "createdAt": timestamp,
            "author": "trial-provisioner",
        },
        {
            "pk": f"TENANT#{tenant}",
            "sk": "POLICY_VERSION#policy-safe-default:00000000000000000001",
            **base,
            "id": "policy-safe-default:00000000000000000001",
            "policy_id": "policy-safe-default",
            "organization_id": "org-trial",
            "version": 1,
            "base_version": 0,
            "name": "Safe default policy",
            "configuration": safe_policy,
            "content_hash": policy_digest,
            "state": "active",
            "author": "trial-provisioner",
            "created_at": timestamp,
            "activated_by": "trial-provisioner",
            "activated_at": timestamp,
        },
        {
            "pk": f"TENANT#{tenant}",
            "sk": "TEMPLATE#template-safe-default",
            **base,
            "id": "template-safe-default",
            "name": "Safe default",
            "configuration": safe_policy,
            "version": 1,
            "createdAt": timestamp,
            "author": "trial-provisioner",
        },
    ]


def handler(event: dict[str, Any], _context: Any) -> dict[str, Any]:
    """Idempotently create the tenant records and grant scoped UI access."""
    # Keep the provider SDK behind the Lambda execution boundary. The pure
    # policy builder remains usable and testable in core-only SDK installs.
    import boto3

    subject = str(event.get("request", {}).get("userAttributes", {}).get("sub", ""))
    email = str(event.get("request", {}).get("userAttributes", {}).get("email", ""))
    user_pool_id = str(event.get("userPoolId", ""))
    if not subject or not user_pool_id:
        raise ValueError("Cognito subject and user pool are required")
    table = boto3.resource("dynamodb").Table(os.environ["CONTROL_TABLE"])
    existing = table.get_item(
        Key={"pk": f"USER#{subject}", "sk": "TENANT"}, ConsistentRead=True
    ).get("Item")
    if existing:
        return event
    for item in build_trial_records(
        subject, email, trial_days=int(os.environ.get("TRIAL_DAYS", "14"))
    ):
        table.put_item(Item=item)
    # Group membership is the coarse RBAC gate; _tenant still enforces the
    # per-user mapping on every API request, preventing cross-tenant access.
    boto3.client("cognito-idp").admin_add_user_to_group(
        UserPoolId=user_pool_id,
        Username=str(event.get("userName", subject)),
        GroupName="platform-admin",
    )
    return event
